name: Close Issues
on: workflow_dispatch

jobs:
  close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq
       
      - name: Get repository url
        env:
          REPOSITORY_API_URL: ${{ github.event.repository.url }}
        run: echo $REPOSITORY_API_URL
        
      - name: Get all opened issues
        id: opened_issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          ISSUES_URL="${REPOSITORY_API_URL}/issues"
          OPEN_ISSUES="${ISSUES_URL}?q=state:open+type:issues+creator:jerichobotactions"

          echo "Pulling issues"
          # $ISSUES=$( curl -s -H "Authorization: token $GITHUB_TOKEN" "'$OPEN_ISSUES'" | jq .number )
          echo "::set-output name=issues::$ISSUES_URL"

      - name: Comment, close, and lock issue if keywords found
        if: steps.opened_issues.outputs.issues != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          $ISSUES=${{ steps.opened_issues.outputs.issues }}
          echo $ISSUES
