name: Close Issues
on: workflow_dispatch

jobs:
  close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ github.event.repository.issues_url }}
        run: echo "$GITHUB_CONTEXT"
